import type { Animal, PlanetTask } from "../types";

export interface TaskTemplate {
  id: string;
  name: string;
  germanName: string;
  description: (target: number, animalName?: string, animalEmoji?: string) => string;
  germanDescription: (target: number, animalName?: string, animalEmoji?: string) => string;
  type: string;
  minLevel: number;
  targetFormula: (level: number, prestige: number) => number;
  targetAnimalId?: string;
  isCumulative?: boolean;
}

export const TASK_TEMPLATES: TaskTemplate[] = [
  // --- 1. Total Animals ---
  {
    id: "animals_count_tot",
    name: "Cuddle Oasis",
    germanName: "Kuscheloase",
    description: (t) => `Have a total of ${t} animals on your planet.`,
    germanDescription: (t) => `Erreiche insgesamt ${t} Tiere auf deinem Planeten.`,
    type: "animals_count",
    minLevel: 1,
    targetFormula: (lv, pr) => Math.floor((30 + lv * 20 + lv * lv * 1.5) * (1 + pr * 0.5)),
    isCumulative: true,
  },
  // --- 2. Clicks (Planet Clicking) ---
  {
    id: "clicks_planet",
    name: "Starquake",
    germanName: "Sternenbeben",
    description: (t) => `Click the planet ${t} times to charge it with energy.`,
    germanDescription: (t) => `Klicke ${t}-mal auf den Planeten, um ihn mit Energie zu versorgen.`,
    type: "clicks",
    minLevel: 1,
    targetFormula: (lv, pr) => Math.floor((40 + lv * 40 + lv * lv * lv * 0.1) * (1 + pr * 0.5)),
  },
  {
    id: "clicks_planet_rhythm",
    name: "Heartbeat",
    germanName: "Herzensimpuls",
    description: (t) => `Perform ${t} rhythmic clicks on the planet.`,
    germanDescription: (t) => `Führe ${t} rhythmische Klicks auf dem Planeten aus.`,
    type: "clicks",
    minLevel: 3,
    targetFormula: (lv, pr) => Math.floor((60 + lv * 50 + lv * lv * 3) * (1 + pr * 0.4)),
  },
  // --- 3. No Click (Idle) ---
  {
    id: "no_click_duration",
    name: "Silent Meditation",
    germanName: "Stille Meditation",
    description: (t) => `Let the planet generate life for ${t} seconds without clicking.`,
    germanDescription: (t) =>
      `Lass den Planeten ${t} Sekunden lang Leben generieren, ohne zu klicken.`,
    type: "no_click_produce",
    minLevel: 1,
    targetFormula: (lv) => Math.min(180, Math.floor(30 + lv * 6)),
  },
  {
    id: "no_click_zen",
    name: "Flowing Cosmic Zen",
    germanName: "Fließendes Kosmos-Zen",
    description: (t) => `Meditate for ${t} seconds without clicking.`,
    germanDescription: (t) => `Halte eine Meditationsphase von ${t} Sekunden ein, ohne zu klicken.`,
    type: "no_click_produce",
    minLevel: 8,
    targetFormula: (lv) => Math.min(240, Math.floor(45 + lv * 8)),
  },
  // --- 4. Missions Claimed ---
  {
    id: "missions_completed_base",
    name: "Mission Readiness",
    germanName: "Missionsbereitschaft",
    description: (t) => `Complete ${t} galactic missions through the radio terminal.`,
    germanDescription: (t) => `Schließe ${t} galaktische Missionen über das Funkterminal ab.`,
    type: "missions_completed",
    minLevel: 1,
    targetFormula: (lv, pr) => Math.max(1, Math.floor((1 + lv * 0.7) * (1 + pr * 0.3))),
  },
  {
    id: "missions_completed_master",
    name: "Pioneering Work",
    germanName: "Pionierarbeit",
    description: (t) => `Complete ${t} radio mission assignments.`,
    germanDescription: (t) => `Erfülle ${t} Missionsaufträge über das Funkterminal.`,
    type: "missions_completed",
    minLevel: 10,
    targetFormula: (lv, pr) => Math.floor((3 + lv * 1.1) * (1 + pr * 0.3)),
  },
  // --- 5. Events Won ---
  {
    id: "events_won_explorer",
    name: "Phenomenon Explorer",
    germanName: "Phänomen-Erforscher",
    description: (t) => `Successfully investigate or resolve ${t} random space events.`,
    germanDescription: (t) => `Untersuche oder löse ${t} zufällige Weltraumereignisse erfolgreich.`,
    type: "events_won",
    minLevel: 2,
    targetFormula: (lv, pr) => Math.max(1, Math.floor((1 + lv * 0.4) * (1 + pr * 0.2))),
  },
  {
    id: "events_won_guardian",
    name: "Cosmic Guardian",
    germanName: "Kosmischer Wächter",
    description: (t) => `Face ${t} planetary events, such as meteorites or auroras.`,
    germanDescription: (t) =>
      `Stelle dich ${t} planetaren Ereignissen, zum Beispiel Meteoriten oder Polarlichtern.`,
    type: "events_won",
    minLevel: 11,
    targetFormula: (lv, pr) => Math.max(2, Math.floor((2 + lv * 0.6) * (1 + pr * 0.2))),
  },
  // --- 6. Star Clicks ---
  {
    id: "collect_stars_catcher",
    name: "Star Catcher",
    germanName: "Sternenfänger",
    description: (t) => `Collect ${t} falling stars by hand.`,
    germanDescription: (t) => `Sammle ${t} herabfallende Sterne von Hand auf.`,
    type: "collect_stars",
    minLevel: 1,
    targetFormula: (lv, pr) => Math.floor((5 + lv * 4 + lv * lv * 0.2) * (1 + pr * 0.4)),
  },
  {
    id: "collect_stars_shower",
    name: "Meteor Shower",
    germanName: "Meteoritenschauer",
    description: (t) => `Use shooting stars to collect ${t} stars.`,
    germanDescription: (t) => `Nutze Sternschnuppen, um ${t} Sterne aufzusammeln.`,
    type: "collect_stars",
    minLevel: 9,
    targetFormula: (lv, pr) => Math.floor((15 + lv * 7 + lv * lv * 0.3) * (1 + pr * 0.4)),
  },
  // --- 7. Alchemy & Crafting ---
  {
    id: "crafting_apprentice",
    name: "Alchemy Apprentice",
    germanName: "Alchemie-Lehrling",
    description: (t) => `Craft a total of ${t} items in the synthesis forge.`,
    germanDescription: (t) => `Stelle insgesamt ${t} Gegenstände in der Syntheseschmiede her.`,
    type: "crafting",
    minLevel: 1,
    targetFormula: (lv, pr) => Math.max(1, Math.floor((1 + lv * 0.6) * (1 + pr * 0.3))),
  },
  {
    id: "crafting_blacksmith",
    name: "Creator's Crown",
    germanName: "Kreatorkrone",
    description: (t) => `Combine resources to craft ${t} refined items.`,
    germanDescription: (t) => `Kombiniere Ressourcen, um ${t} veredelte Gegenstände herzustellen.`,
    type: "crafting",
    minLevel: 10,
    targetFormula: (lv, pr) => Math.floor((3 + lv * 1.2) * (1 + pr * 0.3)),
  },
  // --- 8. Glitter Dust & Moons ---
  {
    id: "glitter_dust_collector",
    name: "Glitter Collector",
    germanName: "Glitzersammler",
    description: (t) =>
      `Collect ${t} units of magical glitter dust at the fairground or through zodiac signs.`,
    germanDescription: (t) =>
      `Sammle ${t} Einheiten magischen Glitzerstaubs auf dem Festgelände oder durch Sternzeichen.`,
    type: "glitter_dust",
    minLevel: 1,
    targetFormula: (lv, pr) => Math.floor((10 + lv * 8 + lv * lv * 0.5) * (1 + pr * 0.5)),
  },
  {
    id: "merge_moons_astronomist",
    name: "Satellite Fusion",
    germanName: "Satellitenverschmelzung",
    description: (t) => `Merge small moons into larger moons ${t} times.`,
    germanDescription: (t) => `Verschmelze ${t}-mal kleine Monde zu größeren Monden.`,
    type: "merge_moons",
    minLevel: 1,
    targetFormula: (lv, pr) => Math.max(1, Math.floor((1 + lv * 0.5) * (1 + pr * 0.2))),
  },

  // --- 9. Specific Animal Targets (35 tasks, bringing the total to exactly 50) ---
  {
    id: "spec_bunny",
    name: "Long-Ear Gathering",
    germanName: "Langohr-Treffen",
    description: (t, n, e) => `Have at least ${t}x ${n} ${e} on your planet.`,
    germanDescription: (t, n, e) => `Besitze mindestens ${t}x ${n} ${e} auf deinem Planeten.`,
    type: "buy_animal",
    minLevel: 1,
    targetFormula: (lv) => Math.floor(10 + lv * 8),
    targetAnimalId: "bunny",
    isCumulative: true,
  },
  {
    id: "spec_chick",
    name: "Feeding Time",
    germanName: "Futterzeit",
    description: (t, n, e) => `Have at least ${t}x ${n} ${e} on your planet.`,
    germanDescription: (t, n, e) => `Besitze mindestens ${t}x ${n} ${e} auf deinem Planeten.`,
    type: "buy_animal",
    minLevel: 1,
    targetFormula: (lv) => Math.floor(8 + lv * 7),
    targetAnimalId: "chick",
    isCumulative: true,
  },
  {
    id: "spec_cat",
    name: "Purring Concert",
    germanName: "Schnurrkonzert",
    description: (t, n, e) => `Have at least ${t}x ${n} ${e} to spread cosmic calm.`,
    germanDescription: (t, n, e) => `Besitze mindestens ${t}x ${n} ${e} für kosmische Beruhigung.`,
    type: "buy_animal",
    minLevel: 2,
    targetFormula: (lv) => Math.floor(6 + lv * 6),
    targetAnimalId: "cat",
    isCumulative: true,
  },
  {
    id: "spec_frog",
    name: "Frog Concert",
    germanName: "Froschkonzert",
    description: (t, n, e) => `Have at least ${t}x ${n} ${e} to populate the ponds.`,
    germanDescription: (t, n, e) =>
      `Besitze mindestens ${t}x ${n} ${e}, um die Teiche zu besiedeln.`,
    type: "buy_animal",
    minLevel: 3,
    targetFormula: (lv) => Math.floor(5 + lv * 5),
    targetAnimalId: "frog",
    isCumulative: true,
  },
  {
    id: "spec_koala",
    name: "Eucalyptus Harvest",
    germanName: "Eukalyptus-Ernte",
    description: (t, n, e) => `Care for ${t}x ${n} ${e} happily munching on leaves.`,
    germanDescription: (t, n, e) => `Sorge für ${t}x ${n} ${e}, die genüsslich Blätter knabbern.`,
    type: "buy_animal",
    minLevel: 4,
    targetFormula: (lv) => Math.floor(5 + lv * 4),
    targetAnimalId: "koala",
    isCumulative: true,
  },
  {
    id: "spec_panda",
    name: "Bamboo Grove",
    germanName: "Bambushain",
    description: (t, n, e) => `Let ${t}x ${n} ${e} roll across the starry meadows.`,
    germanDescription: (t, n, e) => `Lass ${t}x ${n} ${e} durch die Sternenwiesen rollen.`,
    type: "buy_animal",
    minLevel: 5,
    targetFormula: (lv) => Math.floor(4 + lv * 3.5),
    targetAnimalId: "panda",
    isCumulative: true,
  },
  {
    id: "spec_unicorn",
    name: "Rainbow Glow",
    germanName: "Regenbogenglanz",
    description: (t, n, e) => `Let ${t}x ${n} ${e} create their magical rainbows.`,
    germanDescription: (t, n, e) => `Lass ${t}x ${n} ${e} ihre magischen Regenbögen spannen.`,
    type: "buy_animal",
    minLevel: 6,
    targetFormula: (lv) => Math.floor(3 + lv * 3),
    targetAnimalId: "unicorn",
    isCumulative: true,
  },
  {
    id: "spec_hamster",
    name: "Seed Hoard",
    germanName: "Körnervorrat",
    description: (t, n, e) => `Have at least ${t}x ${n} ${e} running in their wheels.`,
    germanDescription: (t, n, e) => `Besitze mindestens ${t}x ${n} ${e} in ihren Laufrädern.`,
    type: "buy_animal",
    minLevel: 7,
    targetFormula: (lv) => Math.floor(3 + lv * 2.5),
    targetAnimalId: "hamster",
    isCumulative: true,
  },
  {
    id: "spec_fox",
    name: "Clever Fox Trail",
    germanName: "Schlauer Fuchspfad",
    description: (t, n, e) => `Lure ${t}x ${n} ${e} from their dens onto the planet.`,
    germanDescription: (t, n, e) => `Locke ${t}x ${n} ${e} aus ihren Bauen auf den Planeten.`,
    type: "buy_animal",
    minLevel: 8,
    targetFormula: (lv) => Math.floor(3 + lv * 2.2),
    targetAnimalId: "fox",
    isCumulative: true,
  },
  {
    id: "spec_bear",
    name: "Bear Power",
    germanName: "Bärenstark",
    description: (t, n, e) => `Have at least ${t}x ${n} ${e} ready for hibernation.`,
    germanDescription: (t, n, e) => `Besitze mindestens ${t}x ${n} ${e} für den Winterschlaf.`,
    type: "buy_animal",
    minLevel: 9,
    targetFormula: (lv) => Math.floor(2 + lv * 1.8),
    targetAnimalId: "bear",
    isCumulative: true,
  },
  {
    id: "spec_alpaca",
    name: "Fluff Parade",
    germanName: "Flauschparade",
    description: (t, n, e) => `Have at least ${t}x ${n} ${e} for a wonderful wool harvest.`,
    germanDescription: (t, n, e) => `Besitze mindestens ${t}x ${n} ${e} für die Wollgewinnung.`,
    type: "buy_animal",
    minLevel: 10,
    targetFormula: (lv) => Math.floor(2 + lv * 1.5),
    targetAnimalId: "alpaca",
    isCumulative: true,
  },
  {
    id: "spec_penguin",
    name: "Ice Floe",
    germanName: "Eisscholle",
    description: (t, n, e) => `Let ${t}x ${n} ${e} settle at the planet's icy pole.`,
    germanDescription: (t, n, e) => `Lass ${t}x ${n} ${e} am eisigen Pol des Planeten siedeln.`,
    type: "buy_animal",
    minLevel: 11,
    targetFormula: (lv) => Math.floor(2 + lv * 1.2),
    targetAnimalId: "penguin",
    isCumulative: true,
  },
  {
    id: "spec_sloth",
    name: "Cosy Living",
    germanName: "Gemütlichkeit",
    description: (t, n, e) => `Have at least ${t}x ${n} ${e} among the starry branches.`,
    germanDescription: (t, n, e) => `Besitze mindestens ${t}x ${n} ${e} in den Sternenästen.`,
    type: "buy_animal",
    minLevel: 12,
    targetFormula: (lv) => Math.floor(1 + lv * 1.1),
    targetAnimalId: "sloth",
    isCumulative: true,
  },
  {
    id: "spec_hedgehog",
    name: "Glitter Spikes",
    germanName: "Glitzerstachel",
    description: (t, n, e) => `Have at least ${t}x ${n} ${e} in your mossy fields.`,
    germanDescription: (t, n, e) => `Besitze mindestens ${t}x ${n} ${e} auf deinen Moosflächen.`,
    type: "buy_animal",
    minLevel: 13,
    targetFormula: (lv) => Math.floor(1 + lv * 1.0),
    targetAnimalId: "hedgehog",
    isCumulative: true,
  },
  {
    id: "spec_seal",
    name: "Seal Applause",
    germanName: "Robbenklatschen",
    description: (t, n, e) => `Care for at least ${t}x ${n} ${e} along your coasts.`,
    germanDescription: (t, n, e) => `Sorge für mindestens ${t}x ${n} ${e} an deinen Küsten.`,
    type: "buy_animal",
    minLevel: 14,
    targetFormula: (lv) => Math.floor(1 + lv * 0.9),
    targetAnimalId: "seal",
    isCumulative: true,
  },
  {
    id: "spec_sheep",
    name: "Cloud Sheep",
    germanName: "Wolkenschaf",
    description: (t, n, e) => `Have at least ${t}x ${n} ${e} in the fluffy pastures.`,
    germanDescription: (t, n, e) => `Besitze mindestens ${t}x ${n} ${e} auf den Flauschweiden.`,
    type: "buy_animal",
    minLevel: 15,
    targetFormula: (lv) => Math.floor(1 + lv * 0.8),
    targetAnimalId: "sheep",
    isCumulative: true,
  },
  {
    id: "spec_otter",
    name: "Otter Cuddles",
    germanName: "Otterkuscheln",
    description: (t, n, e) => `Welcome ${t}x ${n} ${e} to your planet.`,
    germanDescription: (t, n, e) => `Siedle ${t}x ${n} ${e} auf deinem Planeten an.`,
    type: "buy_animal",
    minLevel: 16,
    targetFormula: (lv) => Math.floor(1 + lv * 0.7),
    targetAnimalId: "otter",
    isCumulative: true,
  },
  {
    id: "spec_deer",
    name: "Deer Trail",
    germanName: "Hirschpfad",
    description: (t, n, e) => `Bring ${t}x ${n} ${e} to the woodland clearings.`,
    germanDescription: (t, n, e) => `Bringe ${t}x ${n} ${e} in die bewaldeten Lichtungen.`,
    type: "buy_animal",
    minLevel: 17,
    targetFormula: (lv) => Math.floor(1 + lv * 0.6),
    targetAnimalId: "deer",
    isCumulative: true,
  },
  {
    id: "spec_dino",
    name: "Prehistoric Return",
    germanName: "Urzeit-Rückkehr",
    description: (t, n, e) => `Raise at least ${t}x ${n} ${e} on the planet.`,
    germanDescription: (t, n, e) => `Züchte mindestens ${t}x ${n} ${e} auf dem Planeten.`,
    type: "buy_animal",
    minLevel: 18,
    targetFormula: (lv) => Math.floor(1 + lv * 0.5),
    targetAnimalId: "dino",
    isCumulative: true,
  },
  {
    id: "spec_duck",
    name: "Quacking Concert",
    germanName: "Quakkonzert",
    description: (t, n, e) => `Create a cheerful bustle with ${t}x ${n} ${e}.`,
    germanDescription: (t, n, e) => `Sorge mit ${t}x ${n} ${e} für ein munteres Treiben.`,
    type: "buy_animal",
    minLevel: 19,
    targetFormula: (lv) => Math.floor(1 + lv * 0.4),
    targetAnimalId: "duck",
    isCumulative: true,
  },
  {
    id: "spec_ladybug",
    name: "Lucky Ladybugs",
    germanName: "Glückskäfer",
    description: (t, n, e) => `Have at least ${t}x ${n} ${e} resting on leaves.`,
    germanDescription: (t, n, e) => `Besitze mindestens ${t}x ${n} ${e} auf den Blättern.`,
    type: "buy_animal",
    minLevel: 3,
    targetFormula: (lv) => Math.floor(3 + lv * 4),
    targetAnimalId: "ladybug",
    isCumulative: true,
  },
  {
    id: "spec_bee",
    name: "Honey Treasure",
    germanName: "Honigschatz",
    description: (t, n, e) => `Have at least ${t}x ${n} ${e} making sweet planetary honey.`,
    germanDescription: (t, n, e) => `Besitze mindestens ${t}x ${n} ${e} für süßen Planetenhonig.`,
    type: "buy_animal",
    minLevel: 4,
    targetFormula: (lv) => Math.floor(3 + lv * 3.5),
    targetAnimalId: "bee",
    isCumulative: true,
  },
  {
    id: "spec_pig",
    name: "Happy Squeals",
    germanName: "Glückliches Quieken",
    description: (t, n, e) => `Let ${t}x ${n} ${e} play happily in the mud.`,
    germanDescription: (t, n, e) => `Lass ${t}x ${n} ${e} fröhlich im Matsch spielen.`,
    type: "buy_animal",
    minLevel: 5,
    targetFormula: (lv) => Math.floor(2 + lv * 3),
    targetAnimalId: "pig",
    isCumulative: true,
  },
  {
    id: "spec_puppy",
    name: "Clumsy Playtime",
    germanName: "Tollpatschiges Spiel",
    description: (t, n, e) => `Bring ${t}x ${n} ${e} to the planet to play.`,
    germanDescription: (t, n, e) => `Bringe ${t}x ${n} ${e} zum Spielen auf den Planeten.`,
    type: "buy_animal",
    minLevel: 6,
    targetFormula: (lv) => Math.floor(2 + lv * 2.8),
    targetAnimalId: "puppy",
    isCumulative: true,
  },
  {
    id: "spec_squirrel",
    name: "Nut Stash",
    germanName: "Nussvorrat",
    description: (t, n, e) => `Have at least ${t}x ${n} ${e} in the treetops.`,
    germanDescription: (t, n, e) => `Besitze mindestens ${t}x ${n} ${e} in den Wipfeln.`,
    type: "buy_animal",
    minLevel: 7,
    targetFormula: (lv) => Math.floor(2 + lv * 2.5),
    targetAnimalId: "squirrel",
    isCumulative: true,
  },
  {
    id: "spec_mouse",
    name: "Granary",
    germanName: "Kornkammer",
    description: (t, n, e) => `Have at least ${t}x ${n} ${e} in the meadows.`,
    germanDescription: (t, n, e) => `Besitze mindestens ${t}x ${n} ${e} auf den Wiesen.`,
    type: "buy_animal",
    minLevel: 8,
    targetFormula: (lv) => Math.floor(2 + lv * 2.2),
    targetAnimalId: "mouse",
    isCumulative: true,
  },
  {
    id: "spec_turtle",
    name: "Leisurely Journey",
    germanName: "Gemächliche Reise",
    description: (t, n, e) => `Let ${t}x ${n} ${e} peacefully explore the planet.`,
    germanDescription: (t, n, e) => `Lass ${t}x ${n} ${e} in Ruhe den Planeten erkunden.`,
    type: "buy_animal",
    minLevel: 9,
    targetFormula: (lv) => Math.floor(2 + lv * 2),
    targetAnimalId: "turtle",
    isCumulative: true,
  },
  {
    id: "spec_owl",
    name: "Night Watch",
    germanName: "Nachtwache",
    description: (t, n, e) => `Let ${t}x ${n} ${e} watch over your planet.`,
    germanDescription: (t, n, e) => `Lass ${t}x ${n} ${e} über deinen Planeten wachen.`,
    type: "buy_animal",
    minLevel: 10,
    targetFormula: (lv) => Math.floor(1 + lv * 1.8),
    targetAnimalId: "owl",
    isCumulative: true,
  },
  {
    id: "spec_dolphin",
    name: "Wave Dancers",
    germanName: "Wellentanz",
    description: (t, n, e) => `Let ${t}x ${n} ${e} leap through cosmic waters.`,
    germanDescription: (t, n, e) => `Lass ${t}x ${n} ${e} durch kosmische Gewässer springen.`,
    type: "buy_animal",
    minLevel: 11,
    targetFormula: (lv) => Math.floor(1 + lv * 1.5),
    targetAnimalId: "dolphin",
    isCumulative: true,
  },
  {
    id: "spec_whale",
    name: "Deep-Sea Songs",
    germanName: "Tiefseelieder",
    description: (t, n, e) => `Care for at least ${t}x ${n} ${e} in the planet's ocean.`,
    germanDescription: (t, n, e) => `Sorge für mindestens ${t}x ${n} ${e} im Ozean des Planeten.`,
    type: "buy_animal",
    minLevel: 12,
    targetFormula: (lv) => Math.floor(1 + lv * 1.3),
    targetAnimalId: "whale",
    isCumulative: true,
  },
  {
    id: "spec_butterfly",
    name: "Burst of Color",
    germanName: "Farbenpracht",
    description: (t, n, e) => `Have at least ${t}x ${n} ${e} fluttering through the air.`,
    germanDescription: (t, n, e) => `Besitze mindestens ${t}x ${n} ${e} in der Luft.`,
    type: "buy_animal",
    minLevel: 13,
    targetFormula: (lv) => Math.floor(1 + lv * 1.2),
    targetAnimalId: "butterfly",
    isCumulative: true,
  },
  {
    id: "spec_elephant",
    name: "Gentle Giants",
    germanName: "Sanfte Riesen",
    description: (t, n, e) => `Have at least ${t}x ${n} ${e} roaming the wide savanna.`,
    germanDescription: (t, n, e) => `Besitze mindestens ${t}x ${n} ${e} auf der weiten Savanne.`,
    type: "buy_animal",
    minLevel: 14,
    targetFormula: (lv) => Math.floor(1 + lv * 1.1),
    targetAnimalId: "elephant",
    isCumulative: true,
  },
  {
    id: "spec_tiger",
    name: "Jungle King",
    germanName: "Dschungelkönig",
    description: (t, n, e) => `Care for ${t}x ${n} ${e} among the hidden bushes.`,
    germanDescription: (t, n, e) => `Sorge für ${t}x ${n} ${e} in den verborgenen Büschen.`,
    type: "buy_animal",
    minLevel: 15,
    targetFormula: (lv) => Math.floor(1 + lv * 1.0),
    targetAnimalId: "tiger",
    isCumulative: true,
  },
  {
    id: "spec_lion",
    name: "Sunlit Pride",
    germanName: "Sonnenrudel",
    description: (t, n, e) => `Let ${t}x ${n} ${e} reign over the planet's warm crown.`,
    germanDescription: (t, n, e) => `Lass ${t}x ${n} ${e} in der warmen Planetenkrone thronen.`,
    type: "buy_animal",
    minLevel: 16,
    targetFormula: (lv) => Math.floor(1 + lv * 0.9),
    targetAnimalId: "lion",
    isCumulative: true,
  },
  {
    id: "spec_monkey",
    name: "Canopy Games",
    germanName: "Hangelspiel",
    description: (t, n, e) => `Lure ${t}x ${n} ${e} into the planet's fruit-filled treetops.`,
    germanDescription: (t, n, e) =>
      `Locke ${t}x ${n} ${e} in die fruchtigen Baumwipfel des Planeten.`,
    type: "buy_animal",
    minLevel: 17,
    targetFormula: (lv) => Math.floor(1 + lv * 0.8),
    targetAnimalId: "monkey",
    isCumulative: true,
  },
];

export function rollTaskForLevel(
  level: number,
  prestige: number,
  currentAnimalsList: Animal[],
): PlanetTask {
  // Filter templates eligible for the current level
  const eligible = TASK_TEMPLATES.filter((t) => level >= t.minLevel);
  if (eligible.length === 0) {
    // Fallback if none found, though animals_count_tot is minLevel: 1
    const fallbackTemplate = TASK_TEMPLATES[0];
    const target = Math.max(1, Math.round(fallbackTemplate.targetFormula(level, prestige)));
    return {
      id: fallbackTemplate.id,
      name: fallbackTemplate.name,
      germanName: fallbackTemplate.germanName,
      description: fallbackTemplate.description(target),
      germanDescription: fallbackTemplate.germanDescription(target),
      type: fallbackTemplate.type,
      progress: 0,
      target,
    };
  }

  // Draw a completely random one
  const template = eligible[Math.floor(Math.random() * eligible.length)];
  const target = Math.max(1, Math.round(template.targetFormula(level, prestige)));

  let animalName = "";
  let germanAnimalName = "";
  let animalEmoji = "";
  if (template.targetAnimalId) {
    const animal = currentAnimalsList.find((a) => a.id === template.targetAnimalId);
    if (animal) {
      animalName = animal.name;
      germanAnimalName = animal.germanName;
      animalEmoji = animal.emoji;
    } else {
      animalName = template.targetAnimalId;
      germanAnimalName = template.targetAnimalId;
      animalEmoji = "🐾";
    }
  }

  return {
    id: template.id,
    name: template.name,
    germanName: template.germanName,
    description: template.description(target, animalName, animalEmoji),
    germanDescription: template.germanDescription(target, germanAnimalName, animalEmoji),
    type: template.type,
    progress: 0,
    target,
    targetAnimalId: template.targetAnimalId,
    isCumulative: template.isCumulative,
  };
}
