import type {
  RogueliteBoss,
  RogueliteBossMutation,
  RogueliteBoon,
  RogueliteChoicePreview,
  RogueliteEventDefinition,
  RogueliteNodeType,
  RoguelitePlanetSkin,
  RogueliteRelic,
  RogueliteRunArchetype,
  RogueliteRunModifier,
} from "./types";

export const ROGUELITE_NODE_LABELS: Record<
  RogueliteNodeType,
  { label: string; description: string }
> = {
  boon: {
    label: "Bonus-Station",
    description:
      "Drei funkelnde Boni warten auf dich, mit klaren Sofortwerten und spaeteren Kombinationen.",
  },
  combat: {
    label: "Sternengeplapper",
    description:
      "Ein direkter Test fuer Klicks, Schilde und Bossdruck. Solide Belohnung, solides Risiko.",
  },
  elite: {
    label: "Elite-Sog",
    description:
      "Hoeheres Lebensrisiko gegen Splitter, Kristallstaub und eine deutlich bessere Endtruhe.",
  },
  anomaly: {
    label: "Anomalie",
    description:
      "Instabile Raumfalten mit wilden Mischboni, hoher Spannung und verstecktem Langzeitwert.",
  },
  rest: {
    label: "Rastplatz",
    description:
      "Hier wandelst du Druck in Stabilitaet um: Heilung, Schild oder Vorbereitung fuer spaetere Risiken.",
  },
  merchant: {
    label: "Sternen-Haendler",
    description: "Tausche Kristallstaub gegen gezielte Kraftspitzen oder eine bessere Endtruhe.",
  },
  relic_vault: {
    label: "Reliktkammer",
    description:
      "Ein reiner Wert-Knoten: weniger Sofortkraft, dafuer viel staerkere Endbelohnungen.",
  },
  sacrifice: {
    label: "Opferaltar",
    description:
      "Die brutalsten Entscheidungen des Runs: echter Schmerz gegen besonders wertvolle Belohnungen.",
  },
  echo: {
    label: "Echo-Kammer",
    description:
      "Spiegelt den letzten Bonus-Schritt oder gleicht schiefe Kernwerte fuer spaetere Stationen aus.",
  },
  meteor: {
    label: "Meteorschauer",
    description: "Schneller Staub- und Bossschub, aber fast immer mit spuerbarem Rueckstoss.",
  },
  boss_omen: {
    label: "Boss-Vorzeichen",
    description: "Liefert Bosswissen oder Bossdruck, je nachdem wie frech du den Nebel anfasst.",
  },
};

export const ROGUELITE_RUN_ARCHETYPES: RogueliteRunArchetype[] = [
  {
    id: "anomaly_weaver",
    title: "Anomalie-Weberei",
    description: "Der Run zieht Risse, Echos und weiche Chaos-Entscheidungen magisch an.",
    playstyle: "Flexibler Misch-Build mit Zusatzwert aus Raumfalten.",
  },
  {
    id: "elite_hunter",
    title: "Elite-Jagd",
    description:
      "Gefaehrlichere Routen, aber dafuer mehr Belohnungsdruck und staerkere Truheraeume.",
    playstyle: "Aggressiver Run fuer die Jagd nach Splittern und Relikten.",
  },
  {
    id: "merchant_orbit",
    title: "Haendler-Orbit",
    description: "Mehr Staub, mehr Haendler und feinere Verbesserungs-Zeitfenster.",
    playstyle: "Wirtschaftslastiger Run mit kontrollierten Kraftspitzen.",
  },
  {
    id: "event_bloom",
    title: "Event-Bluete",
    description:
      "Mehr kosmische Zwischenmomente, sanfte Kurswechsel und zusaetzliche Aufbauchancen.",
    playstyle: "Reaktiv und voller kleiner Richtungswechsel.",
  },
  {
    id: "bulwark_spiral",
    title: "Barrieren-Spirale",
    description: "Schild und Sicherheit stehen im Vordergrund, ohne den Bossdruck zu vergessen.",
    playstyle: "Defensiver Skalierungs-Run mit stabilen Kaempfen.",
  },
  {
    id: "glass_comet",
    title: "Glas-Komet",
    description: "Hohe Offensivwerte, duenne Sicherheitsnetze und explosive Belohnungsfenster.",
    playstyle: "Riskanter Explosiv-Run fuer mutige Entscheidungen.",
  },
];

export const ROGUELITE_RUN_MODIFIERS: RogueliteRunModifier[] = [
  {
    id: "glitter_surge",
    title: "Glitzerstrom",
    description: "Stationen schuetten etwas mehr Kristallstaub aus als gewoehnlich.",
    effectLabel: "Mehr Kristallstaub im ganzen Run",
  },
  {
    id: "omen_lens",
    title: "Vorzeichen-Linse",
    description: "Bosswissen und Bossdruck tauchen frueher und haeufiger im Run auf.",
    effectLabel: "Bosskampf frueher relevant",
  },
  {
    id: "soft_shell",
    title: "Weichschale",
    description: "Der Run startet sanfter, will dich spaeter aber fuer zu viel Komfort bestrafen.",
    effectLabel: "Frueh sicher, spaet bissiger",
  },
  {
    id: "cruel_blossom",
    title: "Grausame Bluete",
    description: "Opfer- und Elite-Wert steigen, aber auch der Preis dafuer.",
    effectLabel: "Mehr Wert auf harten Pfaden",
  },
];

export const ROGUELITE_BOON_PREVIEWS: Record<string, RogueliteChoicePreview> = {
  click_plus_50: {
    gains: ["Klickkraft x1.5"],
    costs: [],
    risks: [],
    synergyHint: "Stark fuer Glas-Komet, aggressive Kaempfe und fruehe Klick-Builds.",
    rewardPreview: "Erhoeht deinen aktuellen Klickwert sofort um 50%.",
  },
  first_five_double: {
    gains: ["+6 Bossschaden"],
    costs: [],
    risks: [],
    synergyHint: "Gut, wenn dein Build noch direkten Schaden fuer das Finale braucht.",
    rewardPreview: "Ein sofortiger, verlaesslicher Bossschub.",
  },
  combo_after_ten: {
    gains: ["+7 Klickkraft"],
    costs: [],
    risks: ["+1 Kometendruck"],
    synergyHint: "Stark fuer aggressive Runs, die etwas zusaetzlichen Druck tragen koennen.",
    rewardPreview: "Mehr Klicktempo gegen einen kleinen Druckanstieg.",
  },
  crit_chance_8: {
    gains: ["+8% Crit-Chance"],
    costs: [],
    risks: [],
    synergyHint: "Passt in fast jeden Klick-Build und skaliert gut mit Crit-Power.",
    rewardPreview: "Konstanter Crit-Schub ohne Zusatzkosten.",
  },
  crit_power_125: {
    gains: ["+1.25 Crit-Multiplikator"],
    costs: [],
    risks: [],
    synergyHint: "Am staerksten mit bereits vorhandener Crit-Chance.",
    rewardPreview: "Kritische Treffer werden sofort deutlich staerker.",
  },
  every_third_splitter: {
    gains: ["+10 Bossschaden"],
    costs: [],
    risks: [],
    synergyHint: "Einer der staerksten direkten Abschlussboni fuer offensiv geformte Runs.",
    rewardPreview: "Erhoeht deinen Endkampfwert sofort.",
  },
  clicks_scale_shield: {
    gains: ["+1 Klickkraft je 6 aktuellem Schild"],
    costs: [],
    risks: [],
    synergyHint: "Perfekt fuer Barrieren-Spirale und schildstarke Routen.",
    rewardPreview: "Wandelt deinen aktuellen Schild einmalig in Klickkraft um.",
  },
  clicks_heal_life: {
    gains: ["Heilt bis zu 8 Leben"],
    costs: [],
    risks: [],
    synergyHint: "Flickt aggressive Runs und puffert Opferentscheidungen.",
    rewardPreview: "Stellt sofort aktuelles Leben bis zum Maximum wieder her.",
  },
  animals_x2: {
    gains: ["Passivschaden x2"],
    costs: [],
    risks: [],
    synergyHint: "Massiver Sofortschub fuer passive Builds.",
    rewardPreview: "Verdoppelt deinen aktuellen Passivwert.",
  },
  animals_each_station: {
    gains: ["+1 Passivschaden pro abgeschlossener Station"],
    costs: [],
    risks: [],
    synergyHint: "Skaliert ueber lange Runs und sichere Routen.",
    rewardPreview: "Gibt keinen +3-Sofortbonus, sondern waechst mit jedem Stationsabschluss.",
  },
  elite_passive_double: {
    gains: ["+0.12 Belohnungsmultiplikator"],
    costs: [],
    risks: [],
    synergyHint: "Ideal fuer Elite-Jagd und endbelohnungsstarke Routen.",
    rewardPreview: "Mehr Endtruhenwert statt direkter Kampfkraft.",
  },
  new_animal_shield: {
    gains: ["+18 Schild"],
    costs: [],
    risks: [],
    synergyHint: "Hilft fragilen Passiv-Builds, nicht zu zerplatzen.",
    rewardPreview: "Ein sofortiger defensiver Puffer.",
  },
  animal_boost_per_relic: {
    gains: ["+6 Passivschaden pro aktivem Relikt"],
    costs: [],
    risks: [],
    synergyHint: "Besser, wenn du bereits mehrere aktive Relikte traegst.",
    rewardPreview: "Berechnet den Bonus einmalig aus deinen aktuellen Relikten.",
  },
  idle_stack_patience: {
    gains: ["+8 Passivschaden", "+6 Kristallstaub"],
    costs: [],
    risks: [],
    synergyHint: "Hilft Haendler-Runs und langsameren Schild-Builds.",
    rewardPreview: "Mehr passive Kraft und sofortige Kaufkraft.",
  },
  moon_animals_boss_damage: {
    gains: ["+1 Bossschaden je 4 Passivschaden, aufgerundet"],
    costs: [],
    risks: [],
    synergyHint: "Verbindet einen hohen aktuellen Passivwert mit dem Bossfinish.",
    rewardPreview: "Berechnet den Bossschub einmalig aus deinem aktuellen Passivwert.",
  },
  events_more_often: {
    gains: ["+15% Event-Chance"],
    costs: [],
    risks: [],
    synergyHint: "Perfekt fuer Event-Bluete und flexible Pivot-Runs.",
    rewardPreview: "Mehr Chancen auf kosmische Zwischenereignisse.",
  },
  event_duration_50: {
    gains: ["+10% Event-Chance", "+5 Kristallstaub"],
    costs: [],
    risks: [],
    synergyHint: "Gut fuer Event- und Haendler-Routen.",
    rewardPreview: "Erhoeht die Event-Chance und gibt sofort Staub; keine Dauerveraenderung.",
  },
  anomalies_double_choice: {
    gains: ["+0.05 Belohnungsmultiplikator"],
    costs: [],
    risks: [],
    synergyHint: "Ideal fuer Anomalie-Weberei und wertorientierte Runs.",
    rewardPreview: "Steigert den Endtruhenwert; gibt keine zusaetzliche Anomalie-Wahl.",
  },
  reroll_every_third: {
    gains: ["+1 Reroll"],
    costs: [],
    risks: [],
    synergyHint: "Stark, wenn du gezielt nach bestimmten Build-Linien suchst.",
    rewardPreview: "Ein sofortiger zusaetzlicher Reroll.",
  },
  route_preview_plus_one: {
    gains: ["+1 Purge"],
    costs: [],
    risks: [],
    synergyHint: "Hilft bei Runs mit viel Kometendruck und Fluchlinien.",
    rewardPreview: "Mehr Bereinigung statt zusaetzlicher Routenvorschau.",
  },
  elite_relic_bonus: {
    gains: ["Seltenes Endrelikt garantiert"],
    costs: [],
    risks: [],
    synergyHint: "Stark fuer Runs, die auf die Endbelohnung zielen.",
    rewardPreview: "Garantiert eine seltene Reliktoption in der Endtruhe.",
  },
  boss_telegraph: {
    gains: ["Boss-Mutationen werden sichtbar"],
    costs: [],
    risks: [],
    synergyHint: "Stark fuer Planung und Runs mit knapper Defensive.",
    rewardPreview: "Deckt die aktuellen Boss-Mutationen sofort auf.",
  },
  research_cheaper: {
    gains: ["25% guenstigere Haendler-Kosten"],
    costs: [],
    risks: [],
    synergyHint: "Trifft besonders Haendler-Orbit und staubreiche Routen.",
    rewardPreview: "Senkt alle folgenden Haendlerpreise um 25%.",
  },
  shop_costs_25: {
    gains: ["25% guenstigere Haendler-Kosten"],
    costs: [],
    risks: [],
    synergyHint: "Stapelbar mit weiteren Haendler-Rabatten.",
    rewardPreview: "Senkt alle folgenden Haendlerpreise um 25%.",
  },
  first_shop_free: {
    gains: ["+10 Kristallstaub"],
    costs: [],
    risks: [],
    synergyHint: "Hilft, das naechste Haendlerfenster zu finanzieren.",
    rewardPreview: "Gibt sofort Staub; der erste Kauf wird nicht automatisch gratis.",
  },
  skip_bonus_purge: {
    gains: ["+1 Purge"],
    costs: [],
    risks: [],
    synergyHint: "Gut fuer Runs mit viel Kometendruck und Fluchlinien.",
    rewardPreview: "Gibt sofort ein Werkzeug zur Bereinigung.",
  },
  rest_bonus_shard: {
    gains: ["+1 Bonus-Splitter am Ende"],
    costs: [],
    risks: [],
    synergyHint: "Gut fuer kontrollierte Runs mit Fokus auf die Endtruhe.",
    rewardPreview: "Erhoeht die Endbelohnung sofort um einen Splitter.",
  },
  duplicates_to_dust: {
    gains: ["+12 Kristallstaub"],
    costs: [],
    risks: [],
    synergyHint: "Direkte Kaufkraft fuer den naechsten Haendler.",
    rewardPreview: "Gibt sofort Staub; Duplikate werden nicht dauerhaft umgewandelt.",
  },
  starting_shield_30: {
    gains: ["+30 Schild"],
    costs: [],
    risks: [],
    synergyHint: "Top fuer Schild-Umwandlung und riskante Eliten.",
    rewardPreview: "Gibt sofort 30 Schild.",
  },
  shield_each_station: {
    gains: ["+12 Schild pro abgeschlossener Station"],
    costs: [],
    risks: [],
    synergyHint: "Skaliert mit langen Runs und Schild-zu-Schaden-Effekten.",
    rewardPreview:
      "Gibt keinen einmaligen Sofortbonus, sondern Schild bei jedem Stationsabschluss.",
  },
  shield_burst_aoe: {
    gains: ["+1 Bossschaden je 8 aktuellem Schild"],
    costs: [],
    risks: [],
    synergyHint: "Verbindet einen hohen aktuellen Schildwert mit dem Bossfinish.",
    rewardPreview: "Berechnet den Bossschub einmalig aus deinem aktuellen Schild.",
  },
  boss_damage_minus_20: {
    gains: ["+8 Schild"],
    costs: [],
    risks: [],
    synergyHint: "Ein kleiner Sofortpuffer fuer fragile Runs.",
    rewardPreview: "Gibt 8 Schild; reduziert keinen eingehenden Bossschaden.",
  },
  revive_once: {
    gains: ["+16 aktuelles Leben", "+16 Max-Leben"],
    costs: [],
    risks: [],
    synergyHint: "Stark fuer Hochrisiko-Routen und Opferaltare.",
    rewardPreview: "Erhoeht aktuelles und maximales Leben sofort; keine Wiederbelebung.",
  },
  heal_rest_double: {
    gains: ["+1 Heilcharge"],
    costs: [],
    risks: [],
    synergyHint: "Gibt dir eine weitere kontrollierte Heiloption.",
    rewardPreview: "Eine sofortige Heilcharge; Rastheilung wird nicht verdoppelt.",
  },
  curse_barrier: {
    gains: ["+20 Schild"],
    costs: [],
    risks: [],
    synergyHint: "Puffert riskante Routen sofort ab.",
    rewardPreview: "Gibt sofort 20 Schild, unabhaengig von spaeteren Fluechen.",
  },
  low_life_crit: {
    gains: ["+6% Crit-Chance"],
    costs: [],
    risks: [],
    synergyHint: "Ein verlaesslicher Crit-Schub fuer Klick-Builds.",
    rewardPreview: "Gilt sofort und ist nicht an niedriges Leben gebunden.",
  },
  double_shards_boss_mutation: {
    gains: ["+2 Bonus-Splitter am Ende"],
    costs: [],
    risks: ["+1 Fluchzaehler", "+6 Kometendruck"],
    synergyHint: "Reiner Endtruhen-Greed fuer stabile Runs.",
    rewardPreview: "Hoher Splitter-Payoff gegen deutlich mehr Druck.",
  },
  sacrifice_shield_power: {
    gains: ["+10 Klickkraft"],
    costs: ["-20 Schild"],
    risks: [],
    synergyHint: "Stark, wenn Schild gerade weniger wichtig als Tempo ist.",
    rewardPreview: "Verwandelt bis zu 20 Schild sofort in Klickkraft.",
  },
  lose_life_legendary: {
    gains: ["Seltenes Endrelikt garantiert", "+0.08 Belohnungsmultiplikator"],
    costs: ["-20% aktuelles Leben"],
    risks: ["Kann dich bis auf 1 Leben druecken"],
    synergyHint: "Eine Hochrisiko-Wette fuer stabile Runs mit Lebensreserve.",
    rewardPreview: "Massiv bessere Endbeute gegen sofortigen Lebensverlust.",
  },
  take_curse_skin_roll: {
    gains: ["+1 Bonus-Splitter", "+0.05 Belohnungsmultiplikator"],
    costs: [],
    risks: ["+1 Fluchzaehler"],
    synergyHint: "Stark fuer Belohnungsgier, wenn du den Fluch tragen kannst.",
    rewardPreview: "Mehr Endtruhenwert; gibt keinen zusaetzlichen Skin-Wurf.",
  },
  starrain_autoclick: {
    gains: ["+12 Klickkraft", "+4 Passivschaden"],
    costs: [],
    risks: [],
    synergyHint: "Ein starker vielseitiger Offensivschub.",
    rewardPreview: "Erhoeht beide Offensivwerte sofort; klickt nicht automatisch.",
  },
  even_station_copy: {
    gains: ["+5 Klickkraft", "+5 Passivschaden"],
    costs: [],
    risks: [],
    synergyHint: "Sauberer Verbindungsbonus fuer hybride Builds.",
    rewardPreview: "Gibt beide Werte sofort; kopiert keine spaeteren Boni.",
  },
  highest_feeds_lowest: {
    gains: ["20% des hoechsten Kernwerts fuer den niedrigsten"],
    costs: [],
    risks: [],
    synergyHint: "Repariert schiefe Verteilungen zwischen Klicks, Passiv und Schild.",
    rewardPreview: "Berechnet den Ausgleich einmalig aus deinen aktuellen Werten.",
  },
  freeze_boss_phase: {
    gains: ["+18 Bossschaden"],
    costs: [],
    risks: [],
    synergyHint: "Direkter Abschlussbonus ohne Zusatzkosten.",
    rewardPreview: "Gibt sofort Bossschaden; friert keine Bossphase ein.",
  },
  triad_set_bonus: {
    gains: ["Bei mindestens 3 Kategorien: +6 Klicks, +6 Passiv, +10 Schild"],
    costs: [],
    risks: [],
    synergyHint: "Belohnt breite Build-Pfade mit mindestens zwei bisherigen Kategorien.",
    rewardPreview: "Der Set-Bonus wird einmalig beim Aufnehmen geprueft.",
  },
};

export const ROGUELITE_RELICS: RogueliteRelic[] = [
  {
    id: "kometenherz",
    name: "Kometenherz",
    description: "Du startest mit einem extra Schimmer-Schild.",
    rarity: "rare",
    shortLabel: "+30 Start-Schild",
  },
  {
    id: "pfotenkompass",
    name: "Pfotenkompass",
    description: "Zeigt mehr Infos ueber kommende Wege und Gefahren.",
    rarity: "common",
    shortLabel: "Bessere Routeninfo",
  },
  {
    id: "nebelglas",
    name: "Nebelglas",
    description: "Anomalien tauchen haeufiger auf und sind etwas freundlicher.",
    rarity: "rare",
    shortLabel: "Mehr Anomalien",
  },
  {
    id: "funkelzahn",
    name: "Funkelzahn",
    description: "Mehr Start-Crit-Chance und ein bisschen Crit-Kraft.",
    rarity: "common",
    shortLabel: "+Crit Start",
  },
  {
    id: "mondfaden",
    name: "Mondfaden",
    description: "Schenkt eine freie Heilcharge fuer jeden frischen Run.",
    rarity: "common",
    shortLabel: "+1 Heilcharge",
  },
  {
    id: "splitterbeutel",
    name: "Splitterbeutel",
    description: "Am Ende fallen mehr Galaxie-Splitter aus dem Run.",
    rarity: "rare",
    shortLabel: "+1 End-Splitter",
  },
  {
    id: "sternennaht",
    name: "Sternennaht",
    description: "Jeder Run startet mit einem zusaetzlichen Bonus-Reroll.",
    rarity: "epic",
    shortLabel: "+1 Reroll",
  },
  {
    id: "leerefeder",
    name: "Leerefeder",
    description: "Der Boss wird weicher, dafuer werden normale Stationen bissiger.",
    rarity: "epic",
    shortLabel: "Boss leichter",
  },
];

export const ROGUELITE_PLANET_SKINS: RoguelitePlanetSkin[] = [
  {
    id: "kometenzucker",
    name: "Kometenzucker",
    description: "Suesse Kometenstreifen ueberziehen deinen Hauptplaneten.",
    previewImage: "/assets/planets/18_zuckerstern_garten.webp",
  },
  {
    id: "aurora_bruch",
    name: "Aurora-Bruch",
    description: "Leuchtende Scherben in goldener Nordlicht-Farbe.",
    previewImage: "/assets/planets/09_auroras_goldene_krone.webp",
  },
  {
    id: "mondscherbe",
    name: "Mondscherbe",
    description: "Ein zartes Mondlicht mit silbrigem Glanz.",
    previewImage: "/assets/planets/12_kirschmond_planet.webp",
  },
  {
    id: "nebelflausch",
    name: "Nebelflausch",
    description: "Vertraeumte Wolken und milchige Sternenspuren.",
    previewImage: "/assets/planets/11_sternenwatte_planet.webp",
  },
  {
    id: "sternensirup",
    name: "Sternensirup",
    description: "Warme Karamell-Funken mit kosmischem Glanz.",
    previewImage: "/assets/planets/15_honigstern_planet.webp",
  },
  {
    id: "pfotenorbit",
    name: "Pfotenorbit",
    description: "Pfotenfoermige Umlaufbahnen fuer extra Niedlichkeit.",
    previewImage: "/assets/planets/13_glitzerpfoten_planet.webp",
  },
];

export const ROGUELITE_BOSSES: RogueliteBoss[] = [
  {
    id: "scherbenkomet",
    name: "Scherbenkomet",
    title: "Splittersturm des Nachthimmels",
    description: "Ein rasender Komet, der Schilde aufreissen und Splitter umleiten kann.",
    baseDifficulty: 118,
  },
  {
    id: "schlafwandler_komet",
    name: "Schlafwandler-Komet",
    title: "Der flauschige Finsternisschweif",
    description: "Schiebt deine Heilung weg und drueckt sanften, aber schweren Druck auf den Run.",
    baseDifficulty: 124,
  },
  {
    id: "nebelprisma",
    name: "Nebelprisma",
    title: "Gebrochene Farben im leeren All",
    description: "Verzerrt Krits, passiven Schaden und Rhythmus.",
    baseDifficulty: 128,
  },
  {
    id: "glitch_meteor",
    name: "Glitch-Meteor",
    title: "Knisternder Fehlerkern",
    description: "Ein chaotischer Brocken, der Eventstille und Spiegelbilder erzeugt.",
    baseDifficulty: 132,
  },
];

export const ROGUELITE_BOSS_MUTATIONS: RogueliteBossMutation[] = [
  {
    id: "shield_break",
    name: "Schildbruch",
    description: "Startet den Bosskampf mit weniger Schild.",
  },
  {
    id: "crit_resist",
    name: "Crit-Resistenz",
    description: "Ein Teil deiner Kritkraft verpufft im Raum.",
  },
  {
    id: "event_silence",
    name: "Eventstille",
    description: "Event-Chance hilft im Bosskampf kaum noch.",
  },
  {
    id: "healing_lock",
    name: "Heilungsblock",
    description: "Heilcharges sind im Bosskampf nur halb so stark.",
  },
  {
    id: "splitterregen",
    name: "Splitterregen",
    description: "Der Boss streut Druck, schenkt aber auch mehr End-Splitter.",
  },
  {
    id: "spiegelphase",
    name: "Spiegelphase",
    description: "Dein hoechster Wert wird leicht abgeschwaecht.",
  },
];

export const ROGUELITE_EVENT_POOL: RogueliteEventDefinition[] = [
  {
    id: "saccharin_wormhole",
    title: "Saccharine Wormhole",
    description: "A sweet wormhole offers speed or safety.",
    germanTitle: "Zuckerwurmloch",
    germanDescription: "Ein suesses Wurmloch lockt mit Tempo oder Sicherheit.",
    choices: [
      {
        id: "wormhole_hasten",
        title: "Drink the Momentum",
        description: "Gain 1 reroll and 12 click power, but gain 6 comet pressure.",
        germanTitle: "Tempo trinken",
        germanDescription: "+1 Reroll und +12 Klickkraft, aber +6 Kometendruck.",
      },
      {
        id: "wormhole_anchor",
        title: "Drop Anchor",
        description: "Gain 16 shield and remove 4 comet pressure.",
        germanTitle: "Ankern",
        germanDescription: "+16 Schild und -4 Kometendruck.",
      },
    ],
  },
  {
    id: "dream_petals",
    title: "Dream-Petal Shower",
    description: "Glowing petals can be nurtured or ground into dust.",
    germanTitle: "Traumblatt-Schauer",
    germanDescription: "Leuchtende Blueten wollen gehegt oder zu Staub zermahlen werden.",
    choices: [
      {
        id: "petals_heal",
        title: "Gather Them Over Your Heart",
        description: "Heal up to 22 life and gain 5% event chance.",
        germanTitle: "Ueber dem Herzen sammeln",
        germanDescription: "Heile bis zu 22 Leben und erhalte +5% Event-Chance.",
      },
      {
        id: "petals_trade",
        title: "Grind Them into Dust",
        description: "Gain 18 crystal dust and 1 purge.",
        germanTitle: "Zu Staub zerreiben",
        germanDescription: "+18 Kristallstaub und +1 Purge.",
      },
    ],
  },
  {
    id: "void_kittens",
    title: "Void Kittens",
    description: "Three tiny void kittens offer help for a small sacrifice.",
    germanTitle: "Leere-Kaetzchen",
    germanDescription: "Drei winzige Leere-Kaetzchen bieten Hilfe gegen ein kleines Opfer.",
    choices: [
      {
        id: "kittens_crit",
        title: "Paw Pact",
        description: "Lose 8 life, gain 10% crit chance, and take 1 curse.",
        germanTitle: "Pfotenpakt",
        germanDescription: "-8 Leben, +10% Crit-Chance und +1 Fluchzaehler.",
      },
      {
        id: "kittens_guard",
        title: "Cuddle Guard",
        description: "Gain 24 shield and 1 heal charge.",
        germanTitle: "Kuschelschutz",
        germanDescription: "+24 Schild und +1 Heilcharge.",
      },
    ],
  },
];

export const ROGUELITE_BOONS: RogueliteBoon[] = [
  {
    id: "click_plus_50",
    title: "Click Power +50%",
    description: "Increase your current click power by 50%, rounded.",
    germanTitle: "Klickkraft um 50% erhoehen",
    germanDescription: "Erhoeht deine aktuelle Klickkraft um 50%, gerundet.",
    category: "click",
    rarity: "common",
  },
  {
    id: "first_five_double",
    title: "Boss Damage +6",
    description: "Gain 6 boss damage immediately.",
    germanTitle: "Sechs Bossschaden",
    germanDescription: "Erhalte sofort +6 Bossschaden.",
    category: "click",
    rarity: "rare",
  },
  {
    id: "combo_after_ten",
    title: "Risky Click Boost",
    description: "Gain 7 click power and 1 comet pressure.",
    germanTitle: "Riskanter Klickschub",
    germanDescription: "Erhalte +7 Klickkraft und +1 Kometendruck.",
    category: "click",
    rarity: "rare",
  },
  {
    id: "crit_chance_8",
    title: "Crit Chance +8%",
    description: "Gain 8% crit chance.",
    germanTitle: "Acht Prozent Crit-Chance",
    germanDescription: "Erhalte +8% Crit-Chance.",
    category: "click",
    rarity: "common",
  },
  {
    id: "crit_power_125",
    title: "Crit Power +1.25",
    description: "Increase your crit multiplier by 1.25.",
    germanTitle: "Crit-Power um 1.25 erhoehen",
    germanDescription: "Erhoehe deinen Crit-Multiplikator um 1.25.",
    category: "click",
    rarity: "rare",
  },
  {
    id: "every_third_splitter",
    title: "Boss Damage +10",
    description: "Gain 10 boss damage immediately.",
    germanTitle: "Zehn Bossschaden",
    germanDescription: "Erhalte sofort +10 Bossschaden.",
    category: "click",
    rarity: "epic",
  },
  {
    id: "clicks_scale_shield",
    title: "Convert Shield to Clicks",
    description: "Gain 1 click power for every 6 shield you currently have.",
    germanTitle: "Schild in Klicks wandeln",
    germanDescription: "Erhalte +1 Klickkraft je 6 Schild, die du aktuell hast.",
    category: "click",
    rarity: "epic",
  },
  {
    id: "clicks_heal_life",
    title: "Heal 8 Life",
    description: "Restore up to 8 current life without increasing maximum life.",
    germanTitle: "8 Leben heilen",
    germanDescription: "Heile bis zu 8 aktuelles Leben, ohne das Max-Leben zu erhoehen.",
    category: "click",
    rarity: "epic",
  },
  {
    id: "animals_x2",
    title: "Double Passive Power",
    description: "Double your current passive power, rounded.",
    germanTitle: "Passivkraft verdoppeln",
    germanDescription: "Verdopple deine aktuelle Passivkraft, gerundet.",
    category: "animals",
    rarity: "common",
  },
  {
    id: "animals_each_station",
    title: "Passive Power per Station",
    description: "Gain 1 passive power after each completed station.",
    germanTitle: "Passivkraft pro Station",
    germanDescription: "Erhalte +1 Passivkraft nach jeder abgeschlossenen Station.",
    category: "animals",
    rarity: "rare",
  },
  {
    id: "elite_passive_double",
    title: "Reward Multiplier +0.12",
    description: "Increase your reward multiplier by 0.12.",
    germanTitle: "Belohnungsmultiplikator um 0.12 erhoehen",
    germanDescription: "Erhoehe deinen Belohnungsmultiplikator um 0.12.",
    category: "animals",
    rarity: "rare",
  },
  {
    id: "new_animal_shield",
    title: "Shield +18",
    description: "Gain 18 shield immediately.",
    germanTitle: "Achtzehn Schild",
    germanDescription: "Erhalte sofort +18 Schild.",
    category: "animals",
    rarity: "common",
  },
  {
    id: "animal_boost_per_relic",
    title: "Passive Power per Relic",
    description: "Gain 6 passive power for each currently active relic.",
    germanTitle: "Passivkraft pro Relikt",
    germanDescription: "Erhalte +6 Passivkraft fuer jedes aktuell aktive Relikt.",
    category: "animals",
    rarity: "rare",
  },
  {
    id: "idle_stack_patience",
    title: "Passive Power and Dust",
    description: "Gain 8 passive power and 6 crystal dust.",
    germanTitle: "Passivkraft und Staub",
    germanDescription: "Erhalte +8 Passivkraft und +6 Kristallstaub.",
    category: "animals",
    rarity: "epic",
  },
  {
    id: "moon_animals_boss_damage",
    title: "Passive Power to Boss Damage",
    description: "Gain boss damage equal to one quarter of your current passive power, rounded up.",
    germanTitle: "Passivkraft zu Bossschaden",
    germanDescription:
      "Erhalte Bossschaden in Hoehe eines Viertels deiner aktuellen Passivkraft, aufgerundet.",
    category: "animals",
    rarity: "epic",
  },
  {
    id: "events_more_often",
    title: "Event Chance +15%",
    description: "Gain 15% event chance.",
    germanTitle: "Fuenfzehn Prozent Event-Chance",
    germanDescription: "Erhalte +15% Event-Chance.",
    category: "tempo",
    rarity: "common",
  },
  {
    id: "event_duration_50",
    title: "Event Chance and Dust",
    description: "Gain 10% event chance and 5 crystal dust.",
    germanTitle: "Event-Chance und Staub",
    germanDescription: "Erhalte +10% Event-Chance und +5 Kristallstaub.",
    category: "tempo",
    rarity: "rare",
  },
  {
    id: "anomalies_double_choice",
    title: "Reward Multiplier +0.05",
    description: "Increase your reward multiplier by 0.05.",
    germanTitle: "Belohnungsmultiplikator um 0.05 erhoehen",
    germanDescription: "Erhoehe deinen Belohnungsmultiplikator um 0.05.",
    category: "tempo",
    rarity: "epic",
  },
  {
    id: "reroll_every_third",
    title: "Extra Reroll",
    description: "Gain 1 reroll immediately.",
    germanTitle: "Extra-Reroll",
    germanDescription: "Erhalte sofort +1 Reroll.",
    category: "tempo",
    rarity: "rare",
  },
  {
    id: "route_preview_plus_one",
    title: "Extra Purge",
    description: "Gain 1 purge immediately.",
    germanTitle: "Extra-Purge",
    germanDescription: "Erhalte sofort +1 Purge.",
    category: "tempo",
    rarity: "common",
  },
  {
    id: "elite_relic_bonus",
    title: "Guaranteed Rare Relic",
    description: "Guarantee a rare relic in the final reward choices.",
    germanTitle: "Seltenes Relikt garantiert",
    germanDescription: "Garantiert ein seltenes Relikt in der finalen Belohnungsauswahl.",
    category: "tempo",
    rarity: "epic",
  },
  {
    id: "boss_telegraph",
    title: "Reveal Boss Mutations",
    description: "Reveal the current boss mutations.",
    germanTitle: "Boss-Mutationen aufdecken",
    germanDescription: "Deckt die aktuellen Boss-Mutationen auf.",
    category: "tempo",
    rarity: "rare",
  },
  {
    id: "research_cheaper",
    title: "Merchant Costs -25%",
    description: "Reduce future merchant costs by 25%.",
    germanTitle: "Haendler-Kosten -25%",
    germanDescription: "Senkt kuenftige Haendler-Kosten um 25%.",
    category: "economy",
    rarity: "common",
  },
  {
    id: "shop_costs_25",
    title: "Merchant Costs -25%",
    description: "Reduce future merchant costs by 25%.",
    germanTitle: "Haendler-Kosten -25%",
    germanDescription: "Senkt kuenftige Haendler-Kosten um 25%.",
    category: "economy",
    rarity: "rare",
  },
  {
    id: "first_shop_free",
    title: "Crystal Dust +10",
    description: "Gain 10 crystal dust immediately.",
    germanTitle: "Zehn Kristallstaub",
    germanDescription: "Erhalte sofort +10 Kristallstaub.",
    category: "economy",
    rarity: "epic",
  },
  {
    id: "skip_bonus_purge",
    title: "Extra Purge",
    description: "Gain 1 purge immediately.",
    germanTitle: "Extra-Purge",
    germanDescription: "Erhalte sofort +1 Purge.",
    category: "economy",
    rarity: "rare",
  },
  {
    id: "rest_bonus_shard",
    title: "Bonus Shard",
    description: "Add 1 bonus galaxy shard to the final reward.",
    germanTitle: "Bonus-Splitter",
    germanDescription: "Fuegt der finalen Belohnung +1 Galaxie-Splitter hinzu.",
    category: "economy",
    rarity: "epic",
  },
  {
    id: "duplicates_to_dust",
    title: "Crystal Dust +12",
    description: "Gain 12 crystal dust immediately.",
    germanTitle: "Zwoelf Kristallstaub",
    germanDescription: "Erhalte sofort +12 Kristallstaub.",
    category: "economy",
    rarity: "common",
  },
  {
    id: "starting_shield_30",
    title: "Shield +30",
    description: "Gain 30 shield immediately.",
    germanTitle: "Dreissig Schild",
    germanDescription: "Erhalte sofort +30 Schild.",
    category: "defense",
    rarity: "common",
  },
  {
    id: "shield_each_station",
    title: "Shield per Station",
    description: "Gain 12 shield after each completed station.",
    germanTitle: "Schild pro Station",
    germanDescription: "Erhalte +12 Schild nach jeder abgeschlossenen Station.",
    category: "defense",
    rarity: "rare",
  },
  {
    id: "shield_burst_aoe",
    title: "Shield to Boss Damage",
    description: "Gain 1 boss damage for every 8 shield you currently have.",
    germanTitle: "Schild zu Bossschaden",
    germanDescription: "Erhalte +1 Bossschaden je 8 Schild, die du aktuell hast.",
    category: "defense",
    rarity: "epic",
  },
  {
    id: "boss_damage_minus_20",
    title: "Shield +8",
    description: "Gain 8 shield immediately.",
    germanTitle: "Acht Schild",
    germanDescription: "Erhalte sofort +8 Schild.",
    category: "defense",
    rarity: "rare",
  },
  {
    id: "revive_once",
    title: "Life and Max Life +16",
    description: "Gain 16 current life and 16 maximum life.",
    germanTitle: "Leben und Max-Leben um 16 erhoehen",
    germanDescription: "Erhalte +16 aktuelles Leben und +16 Max-Leben.",
    category: "defense",
    rarity: "legendary",
  },
  {
    id: "heal_rest_double",
    title: "Extra Heal Charge",
    description: "Gain 1 heal charge immediately.",
    germanTitle: "Extra-Heilcharge",
    germanDescription: "Erhalte sofort +1 Heilcharge.",
    category: "defense",
    rarity: "rare",
  },
  {
    id: "curse_barrier",
    title: "Shield +20",
    description: "Gain 20 shield immediately.",
    germanTitle: "Zwanzig Schild",
    germanDescription: "Erhalte sofort +20 Schild.",
    category: "defense",
    rarity: "epic",
  },
  {
    id: "low_life_crit",
    title: "Crit Chance +6%",
    description: "Gain 6% crit chance immediately.",
    germanTitle: "Sechs Prozent Crit-Chance",
    germanDescription: "Erhalte sofort +6% Crit-Chance.",
    category: "defense",
    rarity: "rare",
  },
  {
    id: "double_shards_boss_mutation",
    title: "Cursed Bonus Shards",
    description: "Gain 2 bonus shards, 1 curse, and 6 comet pressure.",
    germanTitle: "Verfluchte Bonus-Splitter",
    germanDescription: "Erhalte +2 Bonus-Splitter, +1 Fluchzaehler und +6 Kometendruck.",
    category: "risk",
    rarity: "legendary",
  },
  {
    id: "sacrifice_shield_power",
    title: "Trade Shield for Clicks",
    description: "Gain 10 click power and lose up to 20 shield.",
    germanTitle: "Schild fuer Klicks opfern",
    germanDescription: "Erhalte +10 Klickkraft und verliere bis zu 20 Schild.",
    category: "risk",
    rarity: "epic",
  },
  {
    id: "lose_life_legendary",
    title: "Life for Rare Rewards",
    description:
      "Lose 20% of current life, guarantee a rare relic, and gain 0.08 reward multiplier.",
    germanTitle: "Leben fuer seltene Belohnungen",
    germanDescription:
      "Verliere 20% deines aktuellen Lebens, garantiere ein seltenes Relikt und erhalte +0.08 Belohnungsmultiplikator.",
    category: "risk",
    rarity: "legendary",
  },
  {
    id: "take_curse_skin_roll",
    title: "Curse for Reward Value",
    description: "Gain 1 curse, 1 bonus shard, and 0.05 reward multiplier.",
    germanTitle: "Fluch fuer Belohnungswert",
    germanDescription:
      "Erhalte +1 Fluchzaehler, +1 Bonus-Splitter und +0.05 Belohnungsmultiplikator.",
    category: "risk",
    rarity: "epic",
  },
  {
    id: "starrain_autoclick",
    title: "Click and Passive Boost",
    description: "Gain 12 click power and 4 passive power.",
    germanTitle: "Klick- und Passivschub",
    germanDescription: "Erhalte +12 Klickkraft und +4 Passivkraft.",
    category: "exotic",
    rarity: "epic",
  },
  {
    id: "even_station_copy",
    title: "Balanced Power Boost",
    description: "Gain 5 click power and 5 passive power.",
    germanTitle: "Ausgeglichener Kraftschub",
    germanDescription: "Erhalte +5 Klickkraft und +5 Passivkraft.",
    category: "exotic",
    rarity: "legendary",
  },
  {
    id: "highest_feeds_lowest",
    title: "Balance Core Stats",
    description: "Add 20% of your highest current core stat to your lowest core stat.",
    germanTitle: "Kernwerte ausgleichen",
    germanDescription:
      "Addiert 20% deines hoechsten aktuellen Kernwerts zu deinem niedrigsten Kernwert.",
    category: "exotic",
    rarity: "epic",
  },
  {
    id: "freeze_boss_phase",
    title: "Boss Damage +18",
    description: "Gain 18 boss damage immediately.",
    germanTitle: "Achtzehn Bossschaden",
    germanDescription: "Erhalte sofort +18 Bossschaden.",
    category: "exotic",
    rarity: "legendary",
  },
  {
    id: "triad_set_bonus",
    title: "Three-Category Set Bonus",
    description:
      "If you have at least three boon categories, gain 6 click power, 6 passive power, and 10 shield.",
    germanTitle: "Set-Bonus fuer drei Kategorien",
    germanDescription:
      "Wenn du mindestens drei Bonus-Kategorien hast, erhalte +6 Klickkraft, +6 Passivkraft und +10 Schild.",
    category: "exotic",
    rarity: "rare",
  },
];
